export const GET_APPLICATIONS = 'GET_APPLICATIONS';
export const UPDATE_APPLICATION = 'UPDATE_APPLICATION';
export const SEARCH_APPLICATION_ID = 'SEARCH_APPLICATION_ID';
export const ERROR = 'ERROR';
export const SET_LOADING = 'SET_LOADING'
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';